version: 2.1

orbs:
  artifactory: jfrog/artifactory-orb@1.0.1

parameters:
  version:
    type: string
    default: ""

workflows:
  version: 2
  build:
    when:
      not: << pipeline.parameters.version >>
    jobs:
      - artifactory/docker-publish:
          docker-registry: spaceandtime.jfrog.io/dw-docker-local
          docker-steps:
            - run:
                name: Build Image
                command: docker build -f ./Dockerfile . -t $DOCKERTAG
          docker-tag: spaceandtime.jfrog.io/dw-docker-local/datafusion-jdbc:0.1.0-${CIRCLE_BUILD_NUM}
          name: Build DataFusion-JDBC Image
          repository: dw-docker-local
          context: ArtifactoryDW
          filters:
            branches:
              only:
                - master

      - artifactory/docker-publish:
          docker-registry: spaceandtime.jfrog.io/dw-docker-local
          docker-steps:
            - run:
                name: Build Image (Arm64)
                command: |
                  docker version
                  docker run --privileged --rm tonistiigi/binfmt --install all
                  docker buildx version
                  docker buildx ls
                  docker buildx build --platform linux/arm64 -f ./Dockerfile . -t $DOCKERTAG;
          docker-tag: spaceandtime.jfrog.io/dw-docker-local/datafusion-jdbc:0.1.0-${CIRCLE_BUILD_NUM}
          name: Build DataFusion-JDBC Image (Arm64)
          repository: dw-docker-local
          context: ArtifactoryDW
          filters:
            branches:
              only:
                - master
