version: 2.1

orbs:
  artifactory: jfrog/artifactory-orb@1.0.1

parameters:
  version:
    type: string
    default: ""

workflows:
  version: 2
  build:
    when:
      not: << pipeline.parameters.version >>
    jobs:
      - artifactory/docker-publish:
          docker-registry: spaceandtime.jfrog.io/dw-docker-local
          docker-steps:
            - run:
                name: Pull Latest Image for Cache
                command: |
                  docker pull spaceandtime.jfrog.io/dw-docker-local/datafusion-jdbc:latest || true
            - run:
                name: Build Image with Cache
                command: |
                  docker build --cache-from spaceandtime.jfrog.io/dw-docker-local/datafusion-jdbc:latest -f ./Dockerfile . -t $DOCKERTAG
            - run:
                name: Tag and Push Latest Image
                command: |
                  docker tag $DOCKERTAG spaceandtime.jfrog.io/dw-docker-local/datafusion-jdbc:latest
                  docker push spaceandtime.jfrog.io/dw-docker-local/datafusion-jdbc:latest
          docker-tag: spaceandtime.jfrog.io/dw-docker-local/datafusion-jdbc:0.1.0-${CIRCLE_BUILD_NUM}
          name: Build DataFusion-JDBC Image
          repository: dw-docker-local
          context: ArtifactoryDW
          filters:
            branches:
              only:
                - master
